"""reconcile 0001's schema representation with the models

Revision ID: 0023_reconcile_migration_drift
Revises: 0022_volunteer_hours_logs
Create Date: 2026-08-02

`alembic check` has been non-blocking in CI since it was added (see
0002_phase1_hardening) because 0001, the hand-written initial migration,
used a different DDL idiom than the models for two things: it left
server_default-backed columns (created_at, is_active, etc.) nullable at
the database level instead of also declaring NOT NULL, and it expressed
uniqueness as a separately-named UniqueConstraint + a plain index instead
of a single unique index. Neither is a functional bug -- every affected
column already always receives its server_default and no code path ever
writes NULL to one, and uniqueness was already enforced either way, just
via a differently-shaped database object -- but it meant `alembic check`
reported drift against the real models on every single run, so the one
check whose job is "did a later migration forget to match the models"
couldn't be trusted to mean anything. This migration makes 0001's
declared shape match the models exactly, closing that gap.

Autogenerated by `alembic revision --autogenerate`, then reviewed and
renamed to fit this project's numbering. Two things worth knowing before
running this against a real, populated database (not a concern yet --
nothing is deployed):
  - Postgres's ALTER COLUMN ... SET NOT NULL takes an ACCESS EXCLUSIVE
    lock for the length of a full-table scan verifying no existing NULLs.
    Fine on near-empty tables; on a large populated table, do it in a
    maintenance window or split into `ADD CONSTRAINT ... NOT VALID` +
    `VALIDATE CONSTRAINT` instead.
  - The unique-constraint -> unique-index swaps assume no existing
    duplicate values, which was already guaranteed by the constraint
    they're replacing.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0023_reconcile_migration_drift"
down_revision: Union[str, None] = "0022_volunteer_hours_logs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'Appointment Confirmed'::character varying"))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('blog_articles', 'summary',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('blog_articles', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('blog_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaign_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('donations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('events', 'registered_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hospital_partner_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('hospital_partner_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hospitals', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('hospitals', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('hospitals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hospitals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_enquiries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_enquiries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_patient_enquiries_hospital_id', table_name='patient_enquiries')
    op.drop_index('ix_patient_enquiries_status', table_name='patient_enquiries')
    op.drop_constraint('patient_enquiries_enquiry_id_key', 'patient_enquiries', type_='unique')
    op.drop_constraint('patient_enquiries_reference_number_key', 'patient_enquiries', type_='unique')
    op.drop_index('ix_patient_enquiries_enquiry_id', table_name='patient_enquiries')
    op.create_index(op.f('ix_patient_enquiries_enquiry_id'), 'patient_enquiries', ['enquiry_id'], unique=True)
    op.drop_index('ix_patient_enquiries_reference_number', table_name='patient_enquiries')
    op.create_index(op.f('ix_patient_enquiries_reference_number'), 'patient_enquiries', ['reference_number'], unique=True)
    op.alter_column('patient_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('patients_email_key', 'patients', type_='unique')
    op.drop_index('ix_patients_email', table_name='patients')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.alter_column('revoked_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('revoked_tokens_jti_key', 'revoked_tokens', type_='unique')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.alter_column('timeline_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('uploaded_reports', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('volunteer_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('volunteer_hours_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('volunteers', 'available_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('volunteers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('volunteers_email_key', 'volunteers', type_='unique')
    op.drop_index('ix_volunteers_email', table_name='volunteers')
    op.create_index(op.f('ix_volunteers_email'), 'volunteers', ['email'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_volunteers_email'), table_name='volunteers')
    op.create_index('ix_volunteers_email', 'volunteers', ['email'], unique=False)
    op.create_unique_constraint('volunteers_email_key', 'volunteers', ['email'])
    op.alter_column('volunteers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('volunteers', 'available_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('volunteer_hours_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('volunteer_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('uploaded_reports', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('timeline_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_unique_constraint('revoked_tokens_jti_key', 'revoked_tokens', ['jti'])
    op.alter_column('revoked_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_index('ix_patients_email', 'patients', ['email'], unique=False)
    op.create_unique_constraint('patients_email_key', 'patients', ['email'])
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patient_enquiries_reference_number'), table_name='patient_enquiries')
    op.create_index('ix_patient_enquiries_reference_number', 'patient_enquiries', ['reference_number'], unique=False)
    op.drop_index(op.f('ix_patient_enquiries_enquiry_id'), table_name='patient_enquiries')
    op.create_index('ix_patient_enquiries_enquiry_id', 'patient_enquiries', ['enquiry_id'], unique=False)
    op.create_unique_constraint('patient_enquiries_reference_number_key', 'patient_enquiries', ['reference_number'])
    op.create_unique_constraint('patient_enquiries_enquiry_id_key', 'patient_enquiries', ['enquiry_id'])
    op.create_index('ix_patient_enquiries_status', 'patient_enquiries', ['status'], unique=False)
    op.create_index('ix_patient_enquiries_hospital_id', 'patient_enquiries', ['hospital_id'], unique=False)
    op.alter_column('patient_enquiries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_enquiries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hospitals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hospitals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hospitals', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('hospitals', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('hospital_partner_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hospital_partner_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'registered_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('donations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaign_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('blog_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('blog_articles', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('blog_articles', 'summary',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('backup_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'Appointment Confirmed'::character varying"))
